language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install --yes build-essential

script:
  - clang --version
  - gcc --version
  - make
  - make test
  - make -f sharedlib.makefile
  - make -f staticlib.makefile
